# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0002_auto_20160217_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='moduleid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='android.Module'),
        ),
    ]
